//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace CoreServices.DataTransferObjects
{
    
    [DataContract(Name = "deviceDto", Namespace = "" , IsReference = true) ]
    public partial class deviceDto
    {
         #region Primitive Properties
    	
    	[DataMember]
        public virtual int device_id
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual int room_id
        {
     
    		
            get { return _room_id; }
            set
            {
                if (_room_id != value)
                {
                    if (room != null && room.room_id != value)
                    {
                        room = null;
                    }
                    _room_id = value;
                }
            }
        }
        private int _room_id;
    	
    	[DataMember]
        public virtual string device_name
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual string device_serial_number
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual string modified_by
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual Nullable<System.DateTime> created_date
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual Nullable<System.DateTime> modified_date
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual Nullable<sbyte> is_valid
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
    	[DataMember]
        public virtual roomDto room
        {
            get { return _room; }
            set
            {
                if (!ReferenceEquals(_room, value))
                {
                    var previousValue = _room;
                    _room = value;
                    Fixuproom(previousValue);
                }
            }
        }
        private roomDto _room;

        #endregion
        #region Association Fixup
    
        private void Fixuproom(roomDto previousValue)
        {
            if (previousValue != null && previousValue.devices.Contains(this))
            {
                previousValue.devices.Remove(this);
            }
    
            if (room != null)
            {
                if (!room.devices.Contains(this))
                {
                    room.devices.Add(this);
                }
                if (room_id != room.room_id)
                {
                    room_id = room.room_id;
                }
            }
        }

        #endregion
    }
}
