//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("meetingModel", "fk_building", "building", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.building), "room", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.room), true)]
[assembly: EdmRelationshipAttribute("meetingModel", "fk_country", "country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.country), "building", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.building), true)]
[assembly: EdmRelationshipAttribute("meetingModel", "fk_room", "room", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.room), "device", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.device), true)]
[assembly: EdmRelationshipAttribute("meetingModel", "fk_rooms", "room", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.room), "reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.reservation), true)]

#endregion

namespace Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MeetingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MeetingEntities object using the connection string found in the 'MeetingEntities' section of the application configuration file.
        /// </summary>
        public MeetingEntities() : base("name=MeetingEntities", "MeetingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MeetingEntities object.
        /// </summary>
        public MeetingEntities(string connectionString) : base(connectionString, "MeetingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MeetingEntities object.
        /// </summary>
        public MeetingEntities(EntityConnection connection) : base(connection, "MeetingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<building> buildings
        {
            get
            {
                if ((_buildings == null))
                {
                    _buildings = base.CreateObjectSet<building>("buildings");
                }
                return _buildings;
            }
        }
        private ObjectSet<building> _buildings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<country> countries
        {
            get
            {
                if ((_countries == null))
                {
                    _countries = base.CreateObjectSet<country>("countries");
                }
                return _countries;
            }
        }
        private ObjectSet<country> _countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<device> devices
        {
            get
            {
                if ((_devices == null))
                {
                    _devices = base.CreateObjectSet<device>("devices");
                }
                return _devices;
            }
        }
        private ObjectSet<device> _devices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<reservation> reservations
        {
            get
            {
                if ((_reservations == null))
                {
                    _reservations = base.CreateObjectSet<reservation>("reservations");
                }
                return _reservations;
            }
        }
        private ObjectSet<reservation> _reservations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<room> rooms
        {
            get
            {
                if ((_rooms == null))
                {
                    _rooms = base.CreateObjectSet<room>("rooms");
                }
                return _rooms;
            }
        }
        private ObjectSet<room> _rooms;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the buildings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobuildings(building building)
        {
            base.AddObject("buildings", building);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocountries(country country)
        {
            base.AddObject("countries", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the devices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodevices(device device)
        {
            base.AddObject("devices", device);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the reservations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToreservations(reservation reservation)
        {
            base.AddObject("reservations", reservation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorooms(room room)
        {
            base.AddObject("rooms", room);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meetingModel", Name="building")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class building : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new building object.
        /// </summary>
        /// <param name="building_id">Initial value of the building_id property.</param>
        /// <param name="country_id">Initial value of the country_id property.</param>
        public static building Createbuilding(global::System.Int32 building_id, global::System.Int32 country_id)
        {
            building building = new building();
            building.building_id = building_id;
            building.country_id = country_id;
            return building;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 building_id
        {
            get
            {
                return _building_id;
            }
            set
            {
                if (_building_id != value)
                {
                    Onbuilding_idChanging(value);
                    ReportPropertyChanging("building_id");
                    _building_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("building_id");
                    Onbuilding_idChanged();
                }
            }
        }
        private global::System.Int32 _building_id;
        partial void Onbuilding_idChanging(global::System.Int32 value);
        partial void Onbuilding_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 country_id
        {
            get
            {
                return _country_id;
            }
            set
            {
                Oncountry_idChanging(value);
                ReportPropertyChanging("country_id");
                _country_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("country_id");
                Oncountry_idChanged();
            }
        }
        private global::System.Int32 _country_id;
        partial void Oncountry_idChanging(global::System.Int32 value);
        partial void Oncountry_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String building_name
        {
            get
            {
                return _building_name;
            }
            set
            {
                Onbuilding_nameChanging(value);
                ReportPropertyChanging("building_name");
                _building_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("building_name");
                Onbuilding_nameChanged();
            }
        }
        private global::System.String _building_name;
        partial void Onbuilding_nameChanging(global::System.String value);
        partial void Onbuilding_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bulding_address
        {
            get
            {
                return _bulding_address;
            }
            set
            {
                Onbulding_addressChanging(value);
                ReportPropertyChanging("bulding_address");
                _bulding_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bulding_address");
                Onbulding_addressChanged();
            }
        }
        private global::System.String _bulding_address;
        partial void Onbulding_addressChanging(global::System.String value);
        partial void Onbulding_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modified_by
        {
            get
            {
                return _modified_by;
            }
            set
            {
                Onmodified_byChanging(value);
                ReportPropertyChanging("modified_by");
                _modified_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modified_by");
                Onmodified_byChanged();
            }
        }
        private global::System.String _modified_by;
        partial void Onmodified_byChanging(global::System.String value);
        partial void Onmodified_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_date;
        partial void Oncreated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.SByte> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.SByte> value);
        partial void Onis_activeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_building", "room")]
        public EntityCollection<room> rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<room>("meetingModel.fk_building", "room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<room>("meetingModel.fk_building", "room", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_country", "country")]
        public country country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<country>("meetingModel.fk_country", "country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<country>("meetingModel.fk_country", "country").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<country> countryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<country>("meetingModel.fk_country", "country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<country>("meetingModel.fk_country", "country", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meetingModel", Name="country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new country object.
        /// </summary>
        /// <param name="country_id">Initial value of the country_id property.</param>
        public static country Createcountry(global::System.Int32 country_id)
        {
            country country = new country();
            country.country_id = country_id;
            return country;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 country_id
        {
            get
            {
                return _country_id;
            }
            set
            {
                if (_country_id != value)
                {
                    Oncountry_idChanging(value);
                    ReportPropertyChanging("country_id");
                    _country_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("country_id");
                    Oncountry_idChanged();
                }
            }
        }
        private global::System.Int32 _country_id;
        partial void Oncountry_idChanging(global::System.Int32 value);
        partial void Oncountry_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country_name
        {
            get
            {
                return _country_name;
            }
            set
            {
                Oncountry_nameChanging(value);
                ReportPropertyChanging("country_name");
                _country_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country_name");
                Oncountry_nameChanged();
            }
        }
        private global::System.String _country_name;
        partial void Oncountry_nameChanging(global::System.String value);
        partial void Oncountry_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_date;
        partial void Oncreated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modified_by
        {
            get
            {
                return _modified_by;
            }
            set
            {
                Onmodified_byChanging(value);
                ReportPropertyChanging("modified_by");
                _modified_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modified_by");
                Onmodified_byChanged();
            }
        }
        private global::System.String _modified_by;
        partial void Onmodified_byChanging(global::System.String value);
        partial void Onmodified_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.SByte> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.SByte> value);
        partial void Onis_activeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_country", "building")]
        public EntityCollection<building> buildings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<building>("meetingModel.fk_country", "building");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<building>("meetingModel.fk_country", "building", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meetingModel", Name="device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class device : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new device object.
        /// </summary>
        /// <param name="device_id">Initial value of the device_id property.</param>
        /// <param name="room_id">Initial value of the room_id property.</param>
        public static device Createdevice(global::System.Int32 device_id, global::System.Int32 room_id)
        {
            device device = new device();
            device.device_id = device_id;
            device.room_id = room_id;
            return device;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 device_id
        {
            get
            {
                return _device_id;
            }
            set
            {
                if (_device_id != value)
                {
                    Ondevice_idChanging(value);
                    ReportPropertyChanging("device_id");
                    _device_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("device_id");
                    Ondevice_idChanged();
                }
            }
        }
        private global::System.Int32 _device_id;
        partial void Ondevice_idChanging(global::System.Int32 value);
        partial void Ondevice_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 room_id
        {
            get
            {
                return _room_id;
            }
            set
            {
                Onroom_idChanging(value);
                ReportPropertyChanging("room_id");
                _room_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("room_id");
                Onroom_idChanged();
            }
        }
        private global::System.Int32 _room_id;
        partial void Onroom_idChanging(global::System.Int32 value);
        partial void Onroom_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String device_name
        {
            get
            {
                return _device_name;
            }
            set
            {
                Ondevice_nameChanging(value);
                ReportPropertyChanging("device_name");
                _device_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("device_name");
                Ondevice_nameChanged();
            }
        }
        private global::System.String _device_name;
        partial void Ondevice_nameChanging(global::System.String value);
        partial void Ondevice_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String device_serial_number
        {
            get
            {
                return _device_serial_number;
            }
            set
            {
                Ondevice_serial_numberChanging(value);
                ReportPropertyChanging("device_serial_number");
                _device_serial_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("device_serial_number");
                Ondevice_serial_numberChanged();
            }
        }
        private global::System.String _device_serial_number;
        partial void Ondevice_serial_numberChanging(global::System.String value);
        partial void Ondevice_serial_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modified_by
        {
            get
            {
                return _modified_by;
            }
            set
            {
                Onmodified_byChanging(value);
                ReportPropertyChanging("modified_by");
                _modified_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modified_by");
                Onmodified_byChanged();
            }
        }
        private global::System.String _modified_by;
        partial void Onmodified_byChanging(global::System.String value);
        partial void Onmodified_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_date;
        partial void Oncreated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> is_valid
        {
            get
            {
                return _is_valid;
            }
            set
            {
                Onis_validChanging(value);
                ReportPropertyChanging("is_valid");
                _is_valid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_valid");
                Onis_validChanged();
            }
        }
        private Nullable<global::System.SByte> _is_valid;
        partial void Onis_validChanging(Nullable<global::System.SByte> value);
        partial void Onis_validChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_room", "room")]
        public room room
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<room>("meetingModel.fk_room", "room").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<room>("meetingModel.fk_room", "room").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<room> roomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<room>("meetingModel.fk_room", "room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<room>("meetingModel.fk_room", "room", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meetingModel", Name="reservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class reservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new reservation object.
        /// </summary>
        /// <param name="reservation_id">Initial value of the reservation_id property.</param>
        /// <param name="room_id">Initial value of the room_id property.</param>
        public static reservation Createreservation(global::System.Int32 reservation_id, global::System.Int32 room_id)
        {
            reservation reservation = new reservation();
            reservation.reservation_id = reservation_id;
            reservation.room_id = room_id;
            return reservation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 reservation_id
        {
            get
            {
                return _reservation_id;
            }
            set
            {
                if (_reservation_id != value)
                {
                    Onreservation_idChanging(value);
                    ReportPropertyChanging("reservation_id");
                    _reservation_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("reservation_id");
                    Onreservation_idChanged();
                }
            }
        }
        private global::System.Int32 _reservation_id;
        partial void Onreservation_idChanging(global::System.Int32 value);
        partial void Onreservation_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 room_id
        {
            get
            {
                return _room_id;
            }
            set
            {
                Onroom_idChanging(value);
                ReportPropertyChanging("room_id");
                _room_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("room_id");
                Onroom_idChanged();
            }
        }
        private global::System.Int32 _room_id;
        partial void Onroom_idChanging(global::System.Int32 value);
        partial void Onroom_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start_time
        {
            get
            {
                return _start_time;
            }
            set
            {
                Onstart_timeChanging(value);
                ReportPropertyChanging("start_time");
                _start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_time");
                Onstart_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _start_time;
        partial void Onstart_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onstart_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end_time
        {
            get
            {
                return _end_time;
            }
            set
            {
                Onend_timeChanging(value);
                ReportPropertyChanging("end_time");
                _end_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_time");
                Onend_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _end_time;
        partial void Onend_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onend_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_date;
        partial void Oncreated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_rooms", "room")]
        public room room
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<room>("meetingModel.fk_rooms", "room").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<room>("meetingModel.fk_rooms", "room").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<room> roomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<room>("meetingModel.fk_rooms", "room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<room>("meetingModel.fk_rooms", "room", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="meetingModel", Name="room")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class room : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new room object.
        /// </summary>
        /// <param name="room_id">Initial value of the room_id property.</param>
        /// <param name="building_id">Initial value of the building_id property.</param>
        public static room Createroom(global::System.Int32 room_id, global::System.Int32 building_id)
        {
            room room = new room();
            room.room_id = room_id;
            room.building_id = building_id;
            return room;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 room_id
        {
            get
            {
                return _room_id;
            }
            set
            {
                if (_room_id != value)
                {
                    Onroom_idChanging(value);
                    ReportPropertyChanging("room_id");
                    _room_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("room_id");
                    Onroom_idChanged();
                }
            }
        }
        private global::System.Int32 _room_id;
        partial void Onroom_idChanging(global::System.Int32 value);
        partial void Onroom_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 building_id
        {
            get
            {
                return _building_id;
            }
            set
            {
                Onbuilding_idChanging(value);
                ReportPropertyChanging("building_id");
                _building_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("building_id");
                Onbuilding_idChanged();
            }
        }
        private global::System.Int32 _building_id;
        partial void Onbuilding_idChanging(global::System.Int32 value);
        partial void Onbuilding_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> room_capacity
        {
            get
            {
                return _room_capacity;
            }
            set
            {
                Onroom_capacityChanging(value);
                ReportPropertyChanging("room_capacity");
                _room_capacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("room_capacity");
                Onroom_capacityChanged();
            }
        }
        private Nullable<global::System.Int32> _room_capacity;
        partial void Onroom_capacityChanging(Nullable<global::System.Int32> value);
        partial void Onroom_capacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String room_name
        {
            get
            {
                return _room_name;
            }
            set
            {
                Onroom_nameChanging(value);
                ReportPropertyChanging("room_name");
                _room_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("room_name");
                Onroom_nameChanged();
            }
        }
        private global::System.String _room_name;
        partial void Onroom_nameChanging(global::System.String value);
        partial void Onroom_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modified_by
        {
            get
            {
                return _modified_by;
            }
            set
            {
                Onmodified_byChanging(value);
                ReportPropertyChanging("modified_by");
                _modified_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modified_by");
                Onmodified_byChanged();
            }
        }
        private global::System.String _modified_by;
        partial void Onmodified_byChanging(global::System.String value);
        partial void Onmodified_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_date;
        partial void Oncreated_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.SByte> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.SByte> value);
        partial void Onis_activeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_building", "building")]
        public building building
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<building>("meetingModel.fk_building", "building").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<building>("meetingModel.fk_building", "building").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<building> buildingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<building>("meetingModel.fk_building", "building");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<building>("meetingModel.fk_building", "building", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_room", "device")]
        public EntityCollection<device> devices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<device>("meetingModel.fk_room", "device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<device>("meetingModel.fk_room", "device", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("meetingModel", "fk_rooms", "reservation")]
        public EntityCollection<reservation> reservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<reservation>("meetingModel.fk_rooms", "reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<reservation>("meetingModel.fk_rooms", "reservation", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
